appointment/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('users/', include('users.urls')),
    path('record/', include('record.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

record/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('appointments/', views.CreateAppointmentListView.as_view(), name='appointment_list'),
    path('appointment/<int:pk>', views.CreateAppointmentDetailView.as_view(), name='appointment_detail'),

    path('appointment/create/', views.CreateAppointmentCreate.as_view(), name='appointment-create'),
    path('appointment/<int:pk>/update/', views.CreateAppointmentUpdate.as_view(), name='appointment-update'),
    path('appointment/<int:pk>/delete/', views.CreateAppointmentDelete.as_view(), name='appointment-delete'),
]

users/urls.py
from django.urls import path
from . import views
from .views import registration_view



urlpatterns = [
    path('myappointments/', views.AppointmentBookByClientListView.as_view(), name='my-appointment'),

    path('register/', registration_view, name='register'),

]

core/models.py
from django.db import models

# Create your models here.

record/models.py
from django.db import models
import uuid
from django.contrib.auth.models import User
from datetime import date
from django.urls import reverse

# Create your models here.
class CreateAppointment(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    address = models.CharField(max_length=30)
    email = models.EmailField('email', blank=True)
    time_of_appointment = models.TimeField()
    date = models.DateField()

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.first_name}'
    
    def get_absolute_url(self):
        """Returns the url to access a detail record for this appointment."""
        return reverse('appointment_detail', args=[str(self.id)])


class AppointmentInstance(models.Model):
    """ Model representing a specific copy of a book (i.e. that can be borrowed from the library)."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular book across whole library')
    client = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    appointment = models.ForeignKey('CreateAppointment', on_delete=models.SET_NULL, null=True) 


    APPOINTMENT_STATUS = (
        ('Approved', 'Approved'),
        ('Canceled', 'Canceled'),
        ('Pending', 'Pending'),
    )
      
    status = models.CharField(
        max_length=20,
        choices=APPOINTMENT_STATUS,
        blank=True,
        default='Pending',
    )

 
    def __str__(self):
        """String for representing the Model object."""
        return f'{self.id} ({self.appointment})'

users/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser
from django.utils.translation import ugettext_lazy as _
from django.urls import reverse

# Create your models here.

class UserManager(BaseUserManager):
    def create_user(self, username, password, **kwargs):
        if not username:
            raise ValueError('Users must have an username')

        user = self.model(
            username=username,
            email=email,
            **kwargs
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, email, password, **kwargs):
        user = self.create_user(
            username,
            password=password,
        )
        user.is_superuser = True
        user.is_staff = True
        user.save(using=self._db)
        return user

class User(AbstractBaseUser):
    username = models.CharField(max_length=20, unique=True)
    email = models.EmailField('email address', blank=True, unique=True)
    first_name = models.CharField(max_length=50, blank=True)
    last_name = models.CharField(max_length=50, blank=True)
    is_staff = models.BooleanField('staff status', default=False)
    is_active = models.BooleanField(default=True)

    objects = UserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    def get_absolute_url(self):
        """Returns the url to access a particular doctor instance."""
        return reverse('user-detail', args=[str(self.id)])

    def __str__(self):
      return self.username

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import User
from django.urls import reverse
class RegistrationForm(UserCreationForm):
    username = forms.CharField(max_length=30)
    email = forms.EmailField(max_length=30, help_text='Required a valid email address')

    class meta:
        model = User
        fields = ("first_name", "last_name", "email", "username", "password1", "password2")

  

core/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'index.html')

record/views.py
from django.shortcuts import render
from .models import CreateAppointment
from django.views import generic
from django.shortcuts import get_object_or_404
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.
class CreateAppointmentListView(generic.ListView):
    model = CreateAppointment
    context_object_name = 'appointment_list'   # your own name for the list as a template variable
    queryset = CreateAppointment.objects.all() # Get All Appointment
    template_name = 'record/record_list.html'  # Specify your own template name/location
    paginate_by = 10

class CreateAppointmentDetailView(generic.DetailView):
    model = CreateAppointment


class CreateAppointmentCreate(LoginRequiredMixin,CreateView):
    model = CreateAppointment
    fields = '__all__'

class CreateAppointmentUpdate(UpdateView):
    model = CreateAppointment
    fields = '__all__'

class CreateAppointmentDelete(DeleteView):
    model = CreateAppointment
    fields = '__all__'

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from record.models import AppointmentInstance
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.urls import reverse
from django.contrib.auth import login, authenticate
from .models import User
from users.forms import RegistrationForm
from django.contrib.auth.forms import UserCreationForm

# Create your views here.

class AppointmentBookByClientListView(LoginRequiredMixin,generic.ListView):
    model = AppointmentInstance
    template_name ='appointment/appointment_book_by_client.html'
    paginate_by = 10
    
    def get_queryset(self):
        return AppointmentInstance.objects.filter(client=self.request.user)



#User registration

def registration_view(request):
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data('password')
            user = authenticate(username = username, password = password)
            login(request, user)
            return redirect('index')
        else:
            form = RegistrationForm()
        return render(request,'users/register.html', {'form' : form })

record/templates/record/createappointment_detail.html
{% extends 'base_generic.html '%}

{%block content%}
    <div class="container">
        <div class="row  justify-content-center">
          <div class="col">
            Name: {{ createappointment.first_name }} {{ createappointment.last_name }}
          </div>
          <div class="col">
            Email: {{ createappointment.email }}
          </div>
          <div class="col">
            Time: {{ createappointment.time_of_appointment  }}
          </div>
        </div>
        <div class="row">
          <div class="col-6">
            Date: {{ createappointment.date  }}
          </div>
          <div class="col-6">
            who to see: {{ createappointment.who_to_see  }}
          </div>
        </div>
    </div>
    
{%endblock%}

record/templates/record/record_list.html
{% extends 'base_generic.html'%}

{% block content %}
    <h1 class="text-center"> My Appointments</h1>
    {% if appointment_list %}
        <div class="container-fluid">
            <table class="table ">
                <thead class="thead-light">
                <tr>
                    <th scope="col">S/N</th>
                    <th scope="col">First Name</th>
                    <th scope="col">Last Name</th>
                    <th scope="col">Email</th>
                    <th scope="col"> </th>
                </tr>
                </thead>
                <tbody>
            {% for appointment in appointment_list %}
                    <tr>
                        <th scope="row">{{ appointment.pk }}</th>
                        <td>{{ appointment.first_name }}</td>
                        <td>{{ appointment.last_name }}</td>
                        <td>{{ appointment.email }}</td>
                        <td><a class="btn btn-primary" href="{% url 'appointment_detail'  appointment.pk %}" role="button">See details</a></td>
                    </tr>
                </tbody>
            {% endfor %}
                </table>
        </div>
    
        {% else %}
        <p>There are no appointment.</p>
    {% endif%}
        
    {% block pagination %}
    {% if is_paginated %}
        <div class="pagination">
            <span class="page-links">
                {% if page_obj.has_previous %}
                    <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}
                <span class="page-current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
                {% endif %}
            </span>
        </div>
    {% endif %}
  {% endblock %} 
{% endblock %}

templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Appointment</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{%url 'index'%}">Appointment</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-center" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'index' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li>
              <a   class="nav-link"href="{% url 'my-appointment'%}">My Booked Appointment</a>
            </li> 
            <li>
              <a   class="nav-link"href="{% url 'appointment-create'%}">Create Appointment</a>
            </li>
            <li>
              <a   class="nav-link"href="{% url 'register'%}">Register</a>
            </li>
            {% if user.is_authenticated %}
              {%if user.is_staff%}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'appointment_list' %}">Appointment</a>
              {%endif%}
              <li><a   class="nav-link"href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>   
              <li class="nav-item"><a class="nav-link" href=""> {{ user.get_username }}</a></li>   
          {% else %}
            <li class="nav-item"><a class="nav-link" href="{% url 'login'%}?next={{request.path}}">Login</a></li>
           
          {% endif %} 
       
            </li>
          </ul>
        </div>      
      </nav>
      {% block content %}{% endblock %}
  


<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

templates/index.html
{% extends "base_generic.html" %}

{% block content %}
  <div class="row">
    <div class="col">
      <h1>Local Library Home</h1>
    </div>
    <div class="col">
      <p>Welcome to LocalLibrary, a website developed by <em>Mozilla Developer Network</em>!</p>   
    </div>
  </div>
{% endblock %}

templates/record/createappointment_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Doctor?</h1>

<p>Are you sure you want to delete the author: {{ author }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

templates/record/createappointment_form.html
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

users/templates/appointment/appointment_book_by_client.html
{% extends "base_generic.html" %}

{% block content %}
    <h1 class="text-center"> My Booked Appointment</h1>

   
   
    {% if appointmentinstance_list %}
    <div class="container">
      <table class="table">
        <thead class="thead-dark">
          <tr>
            <th scope="col">Appointment</th>
            <th scope="col">Status</th>
            <th scope="col"></th>
          </tr>
        </thead>
        <tbody>
        {% for appointment in appointmentinstance_list %}
          <tr>
            <td>{{ appointment.client }}</td>
            <td>{{ appointment.status }}</td>
            <td><a class="btn btn-danger text-white" href="{% url 'appointment_detail' appointment.appointment.pk %}">Details</a></td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    </div> 
      
    {% else %}
      <p>You have not book Any appointment</p>
    {% endif %}          
{% endblock %}

users/templates/users/register.html
{% extends "base_generic.html" %}

{%block content%}
  <h1>Register</h1>
    <form  method="POST">
      {% csrf_token %}
      {% for field in form %}
        <p>
          {{ field.label_tag }}
          {{ field }}

          {% if field.help_text %}
            <small class="text-warning"> {{ field.help_text}}</small>
          {% endif %}
          {% for error in field.errors %}
            <small class="text-danger"> {{ error }}</small> 
          {% endfor %}
        </p>
      {% endfor %}
      <button type="submit"> Register </button>
    </form>
{% endblock %}